### ISSUE TITLE
For correct Translations 

### ISSUE THREAD

**Issue by Naghual** [taskfreak/tfwp#9]
For correct localization of 'tfk_subfilters' list, in file 'taskfreak\inc\classes\tools.php' I have made some changes.

In function 'form_links':
1. At line 120:

`$str .= '<li class="tfk_selected_filter">'.$label.'</li>';`
must be replaced to:
`$str .= '<li class="tfk_selected_filter">'.__($label, 'taskfreak').'</li>';`
1. At line 123:

`$str .= '<li><a href="'.add_query_arg($name, $p, $url).'">'.$label.'</a></li>';`
must be replaced to:
`$str .= '<li><a href="'.add_query_arg($name, $p, $url).'">'.__($label, 'taskfreak').'</a></li>';`

**Comment by herverenault** [comment]
It's not as simple as that. We use the contextual translation function _x() before we call this function, because in some languages (such as French), we have different translation of the same word, for example:
in inc/models/log.php
    `_x('All', 'updates', 'taskfreak')` => translates to "Toutes" in French
in inc/models/project.php
    `_x('All', 'projects', 'taskfreak')` => translates to "Tous" in French

**Comment by Naghual** [comment]
Ok. Let it be!  ;)
Anyway - is sollution will be provided?

**Comment by herverenault** [comment]
I sent you an e-mail, did you get it?
